

      # Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
 name: myubuntuagentpool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: 'mvn -B package --file pom.xml'
      displayName: 'Build Maven'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/webapp/target'
        artifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'
    - task: dependency-check-build-task@6
      inputs:
          projectName: 'security check'
          scanPath: '**/*.csproj'
          format: 'HTML'
    - task: Docker@2
      inputs:
              containerRegistry: 'prema'
              repository: 'prema6396 / devopsbasics'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
      

 

   

   



