

      # Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
 name: myubuntuagentpool

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: 'mvn -B package --file pom.xml'

      displayName: 'Build Maven'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/webapp/target'
        artifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'

  - job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image'
  pool:
    name: myubuntuagentpool
    
    steps:
    - task: UseJavaVersion@1
      inputs:
      versionSpec: '11'

    - task: Docker@2
      inputs:
      containerRegistry: prema
      repository: prema6396/devopsbasics
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'  # Path to your Dockerfile
      tags: |
        $(Build.BuildId)
        latest

   

   



